mariadb:
    image: mariadb:latest
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dolibarr
    volumes:
      - persistent:/var/lib/mysql
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - mariadb:db
    ports:
        - "8000:80"
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: root
web:
    image: madkira/alpha_dolibarr
    environment:
        DOLI_DB_HOST: mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: root
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'http://0.0.0.0'
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
        - "80:80"
    links:
        - mariadb
    volumes:
        - dolibarr:/var/www/html/
